### ISSUE TITLE
Missing Slides

### ISSUE THREAD

**Issue by pmbittner** [TUBS-ISF/Slides#2]
- [x] [SBTK:ICSME22](https://github.com/SoftVarE-Group/BibTags/blob/03f80cea70499ccf21a218b2e4d78622e1a7a96c/literature.bib#L2084-L2096) @AlexanderSchultheiss 
- [x] [SHN+:SE24](https://github.com/SoftVarE-Group/BibTags/blob/03f80cea70499ccf21a218b2e4d78622e1a7a96c/literature.bib#L345-L358) @SundermannC 
- [x] [SBE+:EASE22](https://github.com/SoftVarE-Group/BibTags/blob/03f80cea70499ccf21a218b2e4d78622e1a7a96c/literature.bib#L2238-L2253) @AlexanderSchultheiss 
- [x] [SBT+:SE22](https://github.com/SoftVarE-Group/BibTags/blob/03f80cea70499ccf21a218b2e4d78622e1a7a96c/literature.bib#L2312-L2325) @AlexanderSchultheiss 
- [ ] [SBG+:MODELS21](https://github.com/SoftVarE-Group/BibTags/blob/03f80cea70499ccf21a218b2e4d78622e1a7a96c/literature.bib#L3019-L3032) @AlexanderSchultheiss 
- [ ] [SBKT:SPLC20](https://github.com/SoftVarE-Group/BibTags/blob/03f80cea70499ccf21a218b2e4d78622e1a7a96c/literature.bib#L4215-L4230) @AlexanderSchultheiss 
- [x] [BTS:SEFM19](https://github.com/SoftVarE-Group/BibTags/blob/03f80cea70499ccf21a218b2e4d78622e1a7a96c/literature.bib#L5323-L5336) @pmbittner

**Comment by AlexanderSchultheiss** [comment]
There are no slides for `SBG+:MODELS21` and `SBTK:SPLC20`. The conferences were cancelled due to Corona. For `SBG+:MODELS21` you can refer to `SBT+:SE22`.
